### PR TITLE
Add an optional extra params for middleware and make setForwardedHeaders optional

### PR DESCRIPTION
**Pull request by gogogoghost**
Reflare auto add forwarded headers in request. It cause some source site refuse the request. For example:[cmx](https://m.cmx.im).

And I think user should be able to custom their own forwarded headers rather than add a default one by auto only.

---

So I add an optional extra params in `useReflare`. User can pass some option to middleware
```js
//for skip adding default forwarded headers
await useReflare({
  provider:'static',
  routeList:[],
  extra:{
    addForwardedHeader:false
  }
});

//for default
await useReflare();
//or
await useReflare({
  provider:'static',
  routeList:[]
});
```

### CODE REVIEW

**Comment by xiaoyang-sde** [comment]
Thanks for your contribution! I will review it soon.

**Comment by xiaoyang-sde** [comment]
Thanks for the update. I think we could just delete the code that adds the forwarded header to the request.

**Comment by gogogoghost** [comment]
> Thanks for the update. I think we could just delete the code that adds the forwarded header to the request.

That is more easy. But this may face some modifications for users of older versions if
they are using these headers. I will update my pr if it's acceessable.

**Comment by xiaoyang-sde** [comment]
> > Thanks for the update. I think we could just delete the code that adds the forwarded header to the request.
> 
> That is more easy. But this may face some modifications for users of older versions if they are using these headers. I will update my pr if it's acceessable.

That makes sense. I think we could let `reflare` delete a header from the request or response when it has an empty value in the configuration. For example:

```ts
reflare.push({
  path: '/*',
  /* ... */
  headers: {
    request: {
      'x-forwarded-for': '', // `reflare` should delete this header
      'x-123': '', // `reflare` should delete this header
    },
  },
});
```

This won't introduce a breaking change to existing users because empty header value is not allowed in the HTTP specification.
Feel free to update this PR or I could make implement this feature by myself.

**Comment by gogogoghost** [comment]
> > > Thanks for the update. I think we could just delete the code that adds the forwarded header to the request.
> > 
> > That is more easy. But this may face some modifications for users of older versions if they are using these headers. I will update my pr if it's acceessable.
> 
> That makes sense. I think we could let `reflare` delete a header from the request or response when it has an empty value in the configuration. For example:
> 
> ```ts
> reflare.push({
>   path: '/*',
>   /* ... */
>   headers: {
>     request: {
>       'x-forwarded-for': '', // `reflare` should delete this header
>       'x-123': '', // `reflare` should delete this header
>     },
>   },
> });
> ```
> 
> This won't introduce a breaking change to existing users because empty header value is not allowed in the HTTP specification.
> Feel free to update this PR or I could make implement this feature by myself.

Greate idea. It would be better if you could implement. Thanks.

**Pull request closed without merging**
